version: '3'

services:
  vdb:
    build:
      context: .
      dockerfile: vdb_docker.df
    ports:
      - "3306:3306"
    expose:
      - "3306"
  uta:
    build:
      context: .
      dockerfile: uta_docker.df
    ports:
      - "5432:5432"
    expose:
      - "5432"
  seqrepo:
    image: biocommons/seqrepo:2018-08-21
    volumes:
      - seqdata:/usr/local/share/seqrepo
    stdin_open: true
    tty: true
  restvv:
    build: .
    depends_on:
      - vdb
      - uta
    volumes:
      - seqdata:/usr/local/share/seqrepo
    ports:
      - "5000:5000"
      - "8000:8000"
      - "8080:8080"

volumes:
  seqdata: